# ============================
# CONFIG GERAL
# ============================
spring.application.name=pub

# ============================
# CONFIG H2
# ============================
<<<<<<< HEAD
# Usando DB em arquivo (mais robusto que memória), corrigindo a URL de 'jdb' para 'jdbc'
=======
# Usando DB em arquivo (mais robusto que memï¿½ria), corrigindo a URL de 'jdb' para 'jdbc'
>>>>>>> 9f6a77b (subindo projeto para fork)
spring.datasource.url=jdbc:h2:file:./database
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.defer-datasource-initialization=true
spring.datasource.username=sa
spring.datasource.password=

<<<<<<< HEAD
# Configurações de JPA (mantidas do HEAD)
=======
# Configuraï¿½ï¿½es de JPA (mantidas do HEAD)
>>>>>>> 9f6a77b (subindo projeto para fork)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ============================
<<<<<<< HEAD
# FORÇAR XML COMO PADRÃO (Da feature Bebida)
# ============================
# Quando não especificar Accept, responde em XML
=======
# FORï¿½AR XML COMO PADRï¿½O (Da feature Bebida)
# ============================
# Quando nï¿½o especificar Accept, responde em XML
>>>>>>> 9f6a77b (subindo projeto para fork)
spring.mvc.contentnegotiation.default-media-type=application/xml
spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.favor-parameter=false